services:
  video_conference.locale_listener:
    class: VideoConference\WebsiteBundle\EventListener\LocaleListener
    arguments: ["%kernel.default_locale%"] #ezt olvassa fel a config.yml-ből
    tags:
      - { name: kernel.event_subscriber }
  
#    video_conference_log_in.example:
#        class: VideoConference\LogInBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
